function data = loadAlphasCSV(filePath,fileName,experiment)
if nargin < 3
    experiment = '10cat';
end
%%
v = version;
fileToRead1 = [filePath,fileName(1:end-4),'.txt'];
% if v(1) == '7';
%     fileToRead1 = [filePath,fileName(1:end-4),'.txt']; %'C:\Users\Seven\Dropbox\IPython Notebooks\PyMVPA\alphaSize.txt';
% else
%     fileToRead1 = 'C:\Users\Raul\Dropbox\IPython Notebooks\PyMVPA\alphaSize.txt';
% end
alphaSize = importdata(fileToRead1);




%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Seven\Dropbox\ipython
%    notebooks\pymvpa\10catIncreasingAlphas.csv Worksheet:
%    10catIncreasingAlphas
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/08 16:27:10

%% Import the data
[~, ~, raw00] = xlsread([filePath,fileName],['B2:B',num2str(alphaSize+1)]);
[~, ~, raw01] = xlsread([filePath,fileName],['E2:G',num2str(alphaSize+1)]);
raw = [raw00,raw01];

%% Create output variable
data = cell2mat(raw);

%% Allocate imported array to column variable names
AlphaANOVA = data(:,1);
MeanPerf = data(:,2);
Subject = data(:,3);
VoxelsN = data(:,4);

%% Clear temporary variables
clearvars data raw columnIndices;

if v(1) == '7';
    [~, ~, untitled] = xlsread(['C:\Users\Seven\Dropbox\ipython notebooks\pymvpa\', fileName],fileName(1:end-4),['C2:D',num2str(alphaSize+1)]);
elseif v(1) == '9';
    [~, ~, untitled] = xlsread(['C:\Users\Hallgato\Dropbox\ipython notebooks\pymvpa\', fileName],fileName(1:end-4),['C2:D',num2str(alphaSize+1)]);
else
    [~, ~, untitled] = xlsread(['C:\Users\Raul\Dropbox\ipython notebooks\pymvpa\', fileName],fileName(1:end-4),['C2:D',num2str(alphaSize+1)]);
end

%[~, ~, untitled] = xlsread('C:\Users\Seven\Dropbox\ipython notebooks\pymvpa\10catIncreasingAlphas.csv','10catIncreasingAlphas','C2:D407');
untitled(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),untitled)) = {''};
for k = 1:alphaSize%size(untitled,1)
    data(k).mask = untitled{k,1};
    data(k).maskType = untitled{k,2};
    data(k).AlphaANOVA = AlphaANOVA(k);
    data(k).MeanPerf = MeanPerf(k);
    data(k).VoxelsN = VoxelsN(k);
    data(k).Subject = Subject(k);
end

if strcmp(experiment,'objects')
    filename = [filePath,fileName];
    delimiter = ',';
    startRow = 2;
    formatSpec = '%*s%*s%*s%*s%*s%*s%f%[^\n\r]';
    fileID = fopen(filename,'r');
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);
    fclose(fileID);
    Subject = dataArray{:, 1};


    %[data.Model] = [data.Subject];
    for k = 1:alphaSize%size(untitled,1)
        data(k).Model = data(k).Subject;
        data(k).Subject = Subject(k);
    end
end
